import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const vocabFile = fs.readFileSync(path.join(__dirname, 'data', 'vocab.ts'), 'utf8');

const userWordList = {
    "Jaunt": "review",
    "Jocular": "review",
    "Kindle": "review",
    "Lament": "review",
    "Lavish": "review",
    "Lax": "review",
    "Meager": "review",
    "Mundane": "review",
    "Naive": "review",
    "Orator": "review",
    "Pacify": "review",
    "Palatable": "review",
    "Parody": "review",
    "Perceptive": "review",
    "Philanthropy": "review",
    "Placid": "review",
    "Pristine": "review",
    "Quaint": "review",
    "Rapport": "review",
    "Rash": "review",
    "Recluse": "review",
    "Rectify": "review",
    "Refurbish": "review",
    "Rejuvenate": "review",
    "Relish": "review",
    "Sedentary": "review",
    "Tangible": "review",
    "Thrifty": "review",
    "Tranquil": "review",
    "Vigilant": "review",
    "Virtuoso": "review",
    "Vitality": "review",
    "Vivacious": "review",
    "Wary": "review",
    "Itinerant": "review",
    "Jaded": "review",
    "Jargon": "review",
    "Jettison": "review",
    "Judicious": "review",
    "Kinetic": "mastered",
    "Labyrinth": "review",
    "Languid": "review",
    "Latent": "review",
    "Lethargic": "review",
    "Lucid": "review",
    "Malleable": "review",
    "Manifest": "review",
    "Mediate": "review",
    "Meticulous": "review",
    "Mitigate": "mastered",
    "Morose": "review",
    "Narcissist": "review",
    "Negligent": "review",
    "Nomadic": "review",
    "Nominal": "review",
    "Nonchalant": "mastered",
    "Oblivious": "review",
    "Obscure": "mastered",
    "Obsolete": "review",
    "Obstinate": "review",
    "Obtrusive": "review",
    "Odious": "review",
    "Ominous": "mastered",
    "Opaque": "review",
    "Ornate": "review",
    "Oscillate": "review",
    "Paradox": "mastered",
    "Paramount": "review",
    "Partisan": "review",
    "Penchant": "review",
    "Pensive": "review",
    "Pertinent": "review",
    "Pervasive": "review",
    "Petulant": "review",
    "Pious": "mastered",
    "Placate": "review",
    "Plethora": "review",
    "Pliant": "review",
    "Pragmatic": "review",
    "Precarious": "review",
    "Precursor": "review",
    "Pretentious": "review",
    "Prevalent": "review",
    "Profuse": "review",
    "Prolific": "mastered",
    "Provincial": "review",
    "Prudence": "mastered",
    "Pungent": "mastered",
    "Punitive": "review",
    "Quell": "review",
    "Raucous": "review",
    "Rebuke": "review",
    "Reciprocate": "review",
    "Refute": "mastered",
    "Reiterate": "review",
    "Relinquish": "review",
    "Repentant": "mastered",
    "Reproach": "review",
    "Resilient": "mastered",
    "Resolute": "review",
    "Revel": "review",
    "Revere": "review",
    "Rotund": "review",
    "Satiate": "review",
    "Scrupulous": "review",
    "Scrutinize": "review",
    "Serendipity": "review",
    "Sobriety": "review",
    "Stagnate": "review",
    "Stoic": "review",
    "Strenuous": "review",
    "Submissive": "mastered",
    "Substantiate": "review",
    "Subtle": "mastered",
    "Succinct": "review",
    "Surly": "review",
    "Surrogate": "review",
    "Tenacious": "review",
    "Terrestrial": "review",
    "Translucent": "review",
    "Uncanny": "review",
    "Undulate": "review",
    "Valor": "review",
    "Veneer": "review",
    "Venerate": "review",
    "Vex": "mastered",
    "Viable": "mastered",
    "Vindicate": "review",
    "Vocation": "review",
    "Volatile": "review",
    "Voluminous": "review",
    "Voracious": "review",
    "Wane": "review",
    "Wayward": "review",
    "Whimsical": "review",
    "Wrath": "review",
    "Zealous": "review",
    "Juxtaposition": "review",
    "Kismet": "review",
    "Knell": "review",
    "Laconic": "mastered",
    "Lampoon": "review",
    "Lassitude": "review",
    "Laud": "review",
    "Levity": "review",
    "Loquacious": "review",
    "Magnanimous": "review",
    "Maudlin": "review",
    "Maverick": "review",
    "Mellifluous": "review",
    "Mendacious": "review",
    "Mercurial": "review",
    "Modicum": "review",
    "Mollify": "review",
    "Munificent": "review",
    "Nadir": "review",
    "Nascent": "review",
    "Nebulous": "review",
    "Nefarious": "review",
    "Neophyte": "review",
    "Noxious": "review",
    "Nuance": "review",
    "Obdurate": "review",
    "Obfuscate": "review",
    "Obsequious": "review",
    "Obtuse": "review",
    "Obviate": "review",
    "Officious": "review",
    "Opulent": "review",
    "Orthodox": "review",
    "Ostentatious": "review",
    "Ostracize": "review",
    "Palliate": "review",
    "Panacea": "review",
    "Paradigm": "review",
    "Paragon": "review",
    "Pariah": "review",
    "Parsimonious": "review",
    "Pathos": "review",
    "Paucity": "review",
    "Pedantic": "review",
    "Pejorative": "review",
    "Penitent": "review",
    "Penury": "review",
    "Perfunctory": "review",
    "Pernicious": "review",
    "Perspicacity": "review",
    "Peruse": "review",
    "Phlegmatic": "review",
    "Platitude": "review",
    "Poignant": "review",
    "Polemic": "review",
    "Preclude": "review",
    "Precocious": "review",
    "Predilection": "review",
    "Presumptuous": "review",
    "Probity": "review",
    "Proclivity": "review",
    "Prodigal": "review",
    "Prodigious": "review",
    "Profane": "review",
    "Profligate": "review",
    "Propensity": "review",
    "Propitious": "review",
    "Prosaic": "review",
    "Protean": "review",
    "Puerile": "review",
    "Pugnacious": "review",
    "Pulchritude": "review",
    "Quandary": "review",
    "Querulous": "review",
    "Quiescent": "review",
    "Quixotic": "review",
    "Quotidian": "review",
    "Rancor": "review",
    "Raze": "review",
    "Recalcitrant": "review",
    "Recapitulate": "review",
    "Redoubtable": "review",
    "Refractory": "review",
    "Remiss": "review",
    "Remuneration": "review",
    "Renounce": "review",
    "Replete": "review",
    "Reprehensible": "review",
    "Reprieve": "review",
    "Repudiate": "review",
    "Repugnant": "review",
    "Rescind": "review",
    "Respite": "review",
    "Resplendent": "review",
    "Restive": "review",
    "Reticent": "review",
    "Revile": "review",
    "Rhapsodize": "review",
    "Rhetoric": "review",
    "Rife": "review",
    "Rostrum": "review",
    "Ruminate": "review",
    "Sacrosanct": "review",
    "Sagacious": "review",
    "Salient": "review",
    "Salubrious": "review",
    "Sanctimonious": "review",
    "Sanguine": "review",
    "Scathing": "review",
    "Scurrilous": "review",
    "Seminal": "review",
    "Servile": "review",
    "Sinuous": "review",
    "Solicitous": "review",
    "Soliloquy": "review",
    "Solipsistic": "review",
    "Somnolent": "review",
    "Sophomoric": "review",
    "Soporific": "review",
    "Specious": "review",
    "Spurious": "review",
    "Staid": "review",
    "Stolid": "review",
    "Strident": "review",
    "Stupefy": "review",
    "Subjugate": "review",
    "Sublime": "review",
    "Subterfuge": "review",
    "Superfluous": "review",
    "Surfeit": "review",
    "Surmise": "review",
    "Surreptitious": "review",
    "Sycophant": "review",
    "Symbiotic": "review",
    "Tacit": "review",
    "Taciturn": "review",
    "Tangential": "review",
    "Tantamount": "review",
    "Temerity": "review",
    "Temperance": "review",
    "Tenable": "review",
    "Tenuous": "review",
    "Terse": "review",
    "Timorous": "review",
    "Tirade": "review",
    "Toady": "review",
    "Tome": "review",
    "Torpid": "review",
    "Tortuous": "review",
    "Tractable": "review",
    "Transgress": "review",
    "Transient": "review",
    "Trepidation": "review",
    "Trite": "review",
    "Truculent": "review",
    "Truncate": "review",
    "Turpitude": "review",
    "Ubiquitous": "review",
    "Umbrage": "review",
    "Unconscionable": "review",
    "Unctuous": "review",
    "Upbraid": "review",
    "Usurp": "review",
    "Utilitarian": "review",
    "Vacillate": "review",
    "Vacuous": "review",
    "Vagary": "review",
    "Vapid": "review",
    "Variegated": "review",
    "Vehement": "review",
    "Venerable": "review",
    "Veracity": "review",
    "Verbose": "review",
    "Verdant": "review",
    "Veritable": "review",
    "Vernacular": "review",
    "Vestige": "review",
    "Vicarious": "review",
    "Vicissitude": "review",
    "Vignette": "review",
    "Vilify": "review",
    "Vindictive": "review",
    "Virulent": "review",
    "Viscous": "review",
    "Visionary": "review",
    "Vituperate": "review",
    "Vociferous": "review",
    "Volition": "review",
    "Voluble": "review",
    "Wanton": "review",
    "Wastrel": "review",
    "Wheedle": "review",
    "Whelp": "review",
    "Whet": "review",
    "Wily": "review",
    "Winsome": "review",
    "Wistful": "review",
    "Wizened": "review",
    "Wynd": "review",
    "Xenophobia": "review",
    "Yoke": "review",
    "Zealot": "review"
};

const reviewWords = Object.entries(userWordList)
    .filter(([_, status]) => status === "review")
    .map(([name, _]) => name);

const regex = /\{ name: '(.+?)', definition: '(.+?)',/g;
const vocab = [];
let match;
while ((match = regex.exec(vocabFile)) !== null) {
    vocab.push({ name: match[1], definition: match[2] });
}

const generateRefinedSentence = (wordName) => {
    const word = vocab.find(v => v.name.toLowerCase() === wordName.toLowerCase());
    if (!word) return null;

    const synIndex = word.definition.indexOf('Synonyms:');
    const exIndex = word.definition.indexOf('(Ex:');

    let defPart = word.definition.substring(0, synIndex !== -1 ? synIndex : (exIndex !== -1 ? exIndex : word.definition.length)).trim().replace(/\.$/, '');
    const synsPart = synIndex !== -1 ? word.definition.substring(synIndex + 9, exIndex !== -1 ? exIndex : word.definition.length).trim().replace(/\.$/, '') : '';
    const examplePart = exIndex !== -1 ? word.definition.substring(exIndex + 4, word.definition.length).trim().replace(/\)$/, '') : '';

    const displayWord = wordName;

    // 1. Definition Intro
    let intro = `${displayWord} refers to ${defPart.toLowerCase()}. `;

    // 2. Synonyms / Explanation
    let explanation = "";
    if (synsPart) {
        const synList = synsPart.split(',').map(s => s.trim()).filter(s => s);
        const synString = synList.length > 1
            ? synList.slice(0, -1).join(', ') + ' or ' + synList[synList.length - 1]
            : synList[0];

        if (synString) {
            explanation = `You'd use it to describe things like a ${synString.toLowerCase()}. `;
        }
    }

    // 3. Example
    let example = examplePart ? `For example, you could say: "${examplePart}" ` : "";

    // 4. Repeated Definition at the end
    const repetition = `${displayWord} refers to ${defPart.toLowerCase()}. `;

    return (intro + explanation + example + repetition).trim() + "[pause] [pause]";
};

const finalRefinedScript = reviewWords.map(generateRefinedSentence).filter(Boolean).join('\n');

fs.writeFileSync(path.join(__dirname, 'review_script_new_batch.txt'), finalRefinedScript);
console.log('File created: review_script_new_batch.txt');
console.log(`Included ${reviewWords.length} words.`);
